services:
  - type: web
    name: spectra-cli
    env: python
    pythonVersion: "3.11.9"
    buildCommand: python3.11 -m pip install --upgrade pip && python3.11 -m pip install -r api/requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    plan: free
    region: singapore

